### ISSUE TITLE
Ruby error on "mestral execute-hook" method

### ISSUE THREAD

**Issue by mikaelrandy** [koraktor/mestral#5]
Hi,

I've installed mestral today, so i have a fresh install.

I have added mestral-tape, and tryed to execute a hooks, but an error happened : 

``` bash
$ mestral add-tape https://github.com/mestral/tape
Successfully cloned tape 'mestral/tape'.
$ mestral list
List of Git hooks
 - check-bundle-outdated
 - check-ruby-syntax
 - check-whitespace
$ mestral execute-hook check-whitespace
/usr/local/mestral/Library/Mestral/mestral/cli.rb:81:in `execute_hook': undefined method `execute' for nil:NilClass (NoMethodError)
    from /usr/local/mestral/Library/Gems/thor/lib/thor/command.rb:27:in `__send__'
    from /usr/local/mestral/Library/Gems/thor/lib/thor/command.rb:27:in `run'
    from /usr/local/mestral/Library/Gems/thor/lib/thor/invocation.rb:120:in `invoke_command'
    from /usr/local/mestral/Library/Gems/thor/lib/thor.rb:363:in `dispatch'
    from /usr/local/mestral/Library/Gems/thor/lib/thor/base.rb:439:in `start'
    from /usr/local/bin/mestral:40
```

Mestral was installed via the simple installation script, on a 2013 MacBook Pro, with 10.8.4 MacOS X.

**Comment by koraktor** [comment]
I guess this should be more clearly explained in the README and on the command line, too.

You probably want to do this:

``` sh
$ mestral enable pre-commit check-whitespace
$ mestral execute-hook pre-commit
```

This will enable the `check-whitespace` hooklet to run during the `pre-commit` hook and run the latter afterwards.

I just pushed a few commits that improve usability, though.

**Comment by mikaelrandy** [comment]
I think erros with complete stack trace are not user-friendly, but the current message is already more understandable.

It remains for me to offer a PR ;)

Thank you for your reactivity

**Comment by koraktor** [comment]
@mikaelrandy I must admit that error handling is pretty rudimental at the moment. PRs are always welcome. :+1:
